// Generated by CoffeeScript 1.4.0
(function() {
  var swap,
    _this = this;

  String.prototype.extract_image_id = function() {
    return this.toString().split('_')[1];
  };

  String.prototype.get_image_path = function() {
    return this.toString().replace('?dl=1', '');
  };

  this.cached = null;

  swap = function() {
    var img, o_href;
    if (location.href.match(/\/photo.php/)) {
      if (jQuery('img#fbPhotoImage').get(0) != null) {
        img = jQuery('img#fbPhotoImage');
        if ((o_href = jQuery('a.fbPhotosPhotoActionsItem[rel="ignore"]').attr('href')) != null) {
          img.attr('src', o_href.get_image_path());
        }
      }
      if (jQuery('#photos_snowlift').get(0) != null) {
        img = jQuery('img.spotlight');
        if (_this.cached !== img.attr('src').extract_image_id() && (img.attr('src').extract_image_id() != null)) {
          _this.cached = img.attr('src').extract_image_id();
          return jQuery.get('https://www.facebook.com/photo.php?fbid=' + img.attr('src').extract_image_id(), function(data) {
            if ((o_href = jQuery(data).find('a.fbPhotosPhotoActionsItem[rel="ignore"]').attr('href')) != null) {
              return img.attr('src', o_href.get_image_path());
            }
          });
        }
      } else {
        return _this.cached = null;
      }
    }
  };

  window.setInterval(swap, 500);

}).call(this);
